docs/api.rst
docs/notebooks/create_own_regions.ipynb
docs/notebooks/mask_multidim.ipynb
docs/notebooks/mask_xarray.ipynb
docs/whats_new.rst
regionmask/core/mask.py
regionmask/core/regions.py
regionmask/core/utils.py
regionmask/test/test_Regions.py
regionmask/test/test_defined_regions.py
regionmask/test/test_mask.py
regionmask/test/test_utils.py

autodetect if wrapping is necessary

---

docs/conf.py

Sometimes the `nbconert` of the methods notebook takes longer than 30 seconds (due to the `%timeit`). This removes the methods relatively silently from the docs. Therefore I increase the timeout to 1 minute. This should no longer be an issue once I remove the legacy method/ backend.

increase timeout nbconvert

---

.github/workflows/ci.yaml
ci/requirements/py36-bare-minimum.yml
docs/whats_new.rst
regionmask/core/mask.py
setup.py

I have noticed that the CI over at https://github.com/jbusecke/cmip6_preprocessing/issues/173 is broken. Some of these changes can be fixed there, but there are some failures that are caused by this package.
This is a rather naive fix for the issue.

Hotfix for failure with newest xarray version

---

ci/requirements/docs.yml
docs/conf.py
docs/whats_new.rst
readthedocs.yml

See pyproj/xarray#4350. This installs regionmask via the `ci/requirements/docs.yml` file on RTD using pip. This will hopefully fix the missing version numbers on RTD.

update regionmask install on RTD

---

docs/whats_new.rst
regionmask/tests/test_defined_regions.py
regionmask/tests/test_mask_defined_regions.py
regionmask/tests/utils.py

Let's see if that put's an end to the time-outs (pytest hanging while collecting the tests). Maybe the tests will at least stop failing silently...

list available defined_regions, refactor tests

---

regionmask/tests/test_mask.py

Follow up to #255: suppress a stray warning in the test suite.

follow up to #255: suppress test warning

---

ci/min_deps_check.py
ci/requirements/docs.yml
ci/requirements/environment.yml
ci/requirements/py36-min-all-deps.yml
docs/installation.rst
docs/notebooks/method.ipynb
docs/whats_new.rst
regionmask/core/mask.py
regionmask/tests/__init__.py
regionmask/tests/test_mask.py
regionmask/tests/test_mask_defined_regions.py

Adds masking using pygeos (which is faster than shapely).

mask with pygeos

---

ci/requirements/docs.yml
docs/conf.py
docs/notebooks/geopandas.ipynb
docs/notebooks/mask_2D.ipynb
docs/notebooks/plotting.ipynb
docs/whats_new.rst
regionmask/tests/utils.py

---
- pin cartopy=0.19 in docs environment
- pin matplotlib=3.4 in docs environment
- monkeypatch url in old cartopy versions in the tests
- fix some of the deprecated `plot` arguments in the docs

re-pin cartopy and matplotlib

---

docs/whats_new.rst
regionmask/core/mask.py
regionmask/core/utils.py
regionmask/tests/test_mask.py

always wrap longitudes

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/linting.yaml

- Give the `ci-additional` and `linting` actions more chance for a cache hit.
- Also `py36-min-all-deps` still sometimes hits timeouts & creates errors. But it is running and aborting at 50% or so, so try with a longer timeout and maybe get a chance to see the errors...

GH actions: more caching, longer timeout

---

.github/workflows/ci-additional.yaml
ci/requirements/py37-bare-minimum.yml
ci/requirements/py37-min-all-deps.yml
docs/installation.rst
docs/whats_new.rst
setup.cfg

drop python 3.6 support

---

docs/whats_new.rst
regionmask/core/plot.py
regionmask/core/regions.py
regionmask/core/utils.py

shapely v1.8 deprecations

---

docs/api.rst
docs/whats_new.rst
regionmask/core/plot.py
regionmask/core/regions.py
regionmask/tests/__init__.py
regionmask/tests/test_plot.py
regionmask/tests/test_segmentize.py

Use a better logic to create nice looking plots on curved cartopy maps - split segments based on it's euclidean distance instead of blindly cutting it into 50 pieces irrespective of it's length. This is only applied on `cartopy.geoaxes.GeoAxes`. Per default  the maximum segment length is 1 (for lat/ lon coords).
The exact formula is given as
```python
mx = np.max(np.abs(coords))
tolerance = 1 if mx == 0 else max(10 ** (int(np.log10(mx)) - 2), 1)
```

plot: segmentize instead of subsample

---

ci/requirements/py37-bare-minimum.yml
docs/whats_new.rst
regionmask/core/mask.py
regionmask/tests/test_create_dataarray.py
regionmask/tests/test_mask.py

I knew there had to be a more elegant way to create the `DataArray` of the mask. Now - when `xr.DataArray` obejects are passed as `lon` and `lat` - it's only 3 lines :blush:. The numpy arrays add some complication but that cannot be avoided.

refactor mask_to_dataarray

---

docs/notebooks/mask_2D.ipynb

Just a small typo correction. 
Thanks for your work. Plan to use regionmask within the next year more intensively.

fix: typo in docs

---

docs/notebooks/mask_2D.ipynb

Just a small typo correction. Thanks for your work.

fix: typo in docs (#303)

---

docs/whats_new.rst
regionmask/defined_regions/_ar6_pre_revisions.py
regionmask/tests/test_defined_regions.py

deprecate ar6 _pre_revisions regions

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/linting.yaml

Should abort the GH action workflow when a new commit is pushed.

GH actions: concurrency

---

regionmask/tests/__init__.py
regionmask/tests/test_plot.py

pytest 7.0.0 deprecates
```python
with pytest.warns(None):
pass
```

use assert_no_warning

---

HOW_TO_RELEASE.md
ci/requirements/docs.yml
docs/README_ipynp_for_RTD
docs/notebooks/mask_2D.ipynb
docs/notebooks/plotting.ipynb
docs/whats_new.rst
regionmask/core/mask.py
regionmask/core/plot.py
regionmask/defined_regions/_natural_earth.py
regionmask/tests/test_mask.py
regionmask/tests/test_plot.py
regionmask/tests/test_segmentize.py
regionmask/tests/utils.py

Fix typos using [codespell](https://github.com/codespell-project/codespell) with the following command:
```bash
codespell --skip=".git,devel" --ignore-words-list "cna,wan,nd" . -w -i 3
```

fix typos (using codespell)

---

ci/requirements/docs.yml
docs/whats_new.rst
readthedocs.yml
regionmask/__init__.py

rtd updates some files which messes up the version number when using :
```
import regionmask
regionmask.__version__
'0.9.0.post1.dev0+g4000597.d20220302'
```
(should be `0.9.0`). This tries the workaround suggested in https://github.com/readthedocs/readthedocs.org/issues/8201#issuecomment-1088728000

rtd: fix dirty version (using `git update-index --assume-unchanged`)

---

readthedocs.yml
regionmask/defined_regions/_natural_earth.py

Fixes failed tests for natural earth ocean basins 50 v5.1.2. This only applies to the cartopy download (which is being deprecated), but cannot yet be removed. I might want to add `natural_earth_v5_1_2` at some point...

fix ocean_basins_50 for ne 5.1.2 (cartopy only)

---

docs/whats_new.rst
regionmask/core/mask.py
regionmask/tests/test_mask.py

This warns if it detects `lon.attrs["units"] == "radians"`.
@aaronspring - do you want to take a look? Would you like to have a function to do the conversion? Or would this rather belong to another package?

warn for radian units

---

docs/whats_new.rst
licences/SCIKIT_LEARN_LICENSE
regionmask/core/_deprecate.py
regionmask/core/_geopandas.py
regionmask/core/plot.py
regionmask/core/regions.py
regionmask/core/utils.py
regionmask/tests/test_deprecate.py
regionmask/tests/test_plot.py
regionmask/tests/test_utils.py

This adds a helper to deprecate any number of positional arguments and deprecates some in for `mask` methods.

make more arguments keyword only

---

docs/whats_new.rst
regionmask/__init__.py

use importlib.metadata if available

---

setup.py

Add `"version_scheme": "no-guess-dev"` to setup.py - so it's really picked up. Not sure why this is actually relevant when we have pyproject.toml file.

version_scheme: no-guess-dev

---

docs/whats_new.rst
regionmask/core/regions.py
regionmask/tests/test_Regions.py

Adds a error when passing a single region to `regioinmask.Regions` - this only partially works when the coordinates are not given as a numpy array or a shapely (Multi)Polygon. This did error before but the message should be better now...

better error when passing single region

---

regionmask/core/_deprecate.py
regionmask/tests/test_deprecate.py

Ensure params are passed on correctly in `_deprecate_positional_args` - see also pydata/xarray#6967

fix _deprecate_positional_args

---

docs/whats_new.rst
regionmask/core/formatting.py
regionmask/core/regions.py
regionmask/tests/test_formatting.py

This does not really close #377 - I could not get the pandas part to work, but the metadata should be truncated a bit more consistently.

tweak Regions.__repr__

---

docs/api.rst
docs/whats_new.rst
regionmask/__init__.py
regionmask/core/options.py
regionmask/core/regions.py
regionmask/tests/test_options.py

Adds `set_options` and `get_options` to regionmask. Currently `"display_max_rows"` is the only option, but more are planned.

add set_options

---

.github/workflows/ci.yaml
docs/whats_new.rst
regionmask/tests/test_defined_regions.py
regionmask/tests/test_mask.py
regionmask/tests/utils.py
setup.cfg

Added a CI run for python 3.11 to see if the tests pass and some additional changes to the tests.

support python 3.11

---

docs/defined_countries.rst
docs/defined_landmask.rst
docs/defined_ocean_basins.rst
docs/whats_new.rst
regionmask/core/options.py
regionmask/defined_regions/_natural_earth.py
regionmask/defined_regions/_ressources.py
regionmask/tests/test_options.py

Allow setting the cache folder via `regionmask.set_options(cache_dir="~/.rmask")`

configurable cache dir

---

docs/whats_new.rst
regionmask/defined_regions/_natural_earth.py
regionmask/tests/test_defined_regions.py
regionmask/tests/utils.py

using a `bbox` to load `us_states_10` and `us_states_50` speeds it up considerably (15 times) as only a small amount of the data must be loaded.

read us_states faster using bbox

---

.github/workflows/ci-additional.yaml
ci/min_deps_check.py
ci/requirements/docs.yml
ci/requirements/environment.yml
ci/requirements/py37-min-all-deps.yml
ci/requirements/py38-min-all-deps.yml
docs/installation.rst
docs/whats_new.rst
regionmask/defined_regions/_natural_earth.py

This should speed up the natural earth data shapefiles - even after #405 (which already sped up the tests from 60s to 15s). Not this one should bring it down from 15s to 2s (assuming the data is already downloaded).

enable pyogrio to read natural earth data

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml

As mamba-org/provision-with-micromamba is being deprecated, switch to mamba-org/setup-micromamba

use mamba-org/setup-micromamba for CI

---

.github/workflows/ci-additional.yaml
ci/requirements/docs.yml
ci/requirements/environment.yml
ci/requirements/py310-shapely_lt_2.yml
docs/installation.rst
docs/notebooks/method.ipynb

Now that shapely 2 is out and generally supported by geopandas and cartopy (in v0.21.1) we can remove mentioning pygeos from the docs. I plan to support pygeos internally until the minimum required shapely version is 2.0 (but as this is internal-only I might change my mind).

remove pygeos from docs & update tests

---

docs/whats_new.rst
regionmask/core/mask.py
regionmask/tests/test_mask.py
setup.cfg

As I am unsure concerning #385 with #386 as alternative I here add a warning if `method` is set. This should allow to remove it earlier.

mark mask method kw as internal

---

docs/whats_new.rst
regionmask/core/utils.py
regionmask/tests/test_Regions.py
regionmask/tests/test_utils.py
regionmask/tests/test_wrapAngle.py

Fix `_wrapAngle(lon, wrap_lon=True)` when `lon` contains `NA` values. Note however, that this bug would not affect users since v0.8.0 (#271). Also simplifies the logic of the function.

fix wrap_lon for NaN & simplify

---

docs/whats_new.rst
regionmask/core/_geopandas.py
regionmask/core/mask.py
regionmask/tests/test_geopandas.py
regionmask/tests/test_mask.py
regionmask/tests/test_mask_cf_xarray.py
regionmask/tests/utils.py

`mask_geopandas` also needs the `use_cf` param - otherwise this behavior cannot be controlled. Also contains doc fixes.

mask_geopandas: pass use_cf

---

docs/notebooks/plotting.ipynb
docs/whats_new.rst
regionmask/core/plot.py
regionmask/tests/test_plot.py

Finalize the deprecations for the plot methods in v0.8.0.

finalize plot deprecations

---

docs/whats_new.rst
regionmask/core/mask.py
regionmask/tests/test_mask.py

Not difficult to fix, but easy to miss... Reminds me very much of #266 (where a `-` was missing)

buxfix for unstructured & overlapping masks

---

regionmask/core/mask.py
regionmask/tests/test_geopandas.py
regionmask/tests/test_mask.py
regionmask/tests/test_wrapAngle.py
regionmask/tests/utils.py

restore numpy 2.0 compatibility

---

regionmask/tests/test_plot.py

fix test for matplotlib v3.8

---

docs/notebooks/overlap.ipynb
docs/whats_new.rst
regionmask/core/_geopandas.py
regionmask/core/mask.py
regionmask/core/regions.py
regionmask/tests/test_geopandas.py
regionmask/tests/test_mask.py

After this PR regionmask no longer assumes regions do not overlap by default. This PR sets `regionmask.Regions(..., overlap=None)` per default. In this case:
- `region.mask(da)` will error if it detects a gridpoint is in more than one region
- `region.mask_3D(da)` will (silently) do the right thing
- this lead to a slightly poorer performance (I guess it's not worth warning about this - should not be too terrible).
- It will _not_ check if the polygons overlap - it will check if any gridpoint belongs to more than one region (the first takes prohibitively long, see https://github.com/regionmask/regionmask/issues/265#issuecomment-912482479)
Maybe `region.mask_3D(da)` should warn if it detects an overlap (because it's a changing behaviour).
The PR should not change the behavior for …

no longer assume non-overlapping regions by default

---

docs/whats_new.rst
regionmask/core/mask.py
regionmask/tests/test_mask.py

BUG: more than 32 overlapping regions using rasterio

---

.github/workflows/ci-additional.yaml
.github/workflows/ci.yaml
.github/workflows/linting.yaml
CHANGELOG.rst
ci/min_deps_check.py
ci/requirements/docs.yml
ci/requirements/py39-bare-minimum.yml
ci/requirements/py39-min-all-deps.yml
docs/installation.rst
regionmask/tests/utils.py
setup.cfg

Drop support for python 3.8 as mandated by NEP 29.

drop python 3.8 support

---

regionmask/__init__.py

ignore __version__ fallback in coverage

---

data/regions_remote_catalog.yaml

It seems that the MEOW regions are no longer available under http://maps.tnc.org. However, I found https://geospatial.tnc.org/datasets/903c3ae05b264c00a3b5e58a4561b7e6/about which points to the data on www.arcgis.com
@aaronspring FYI

fix url for MEOW regions

---

CHANGELOG.rst
docs/api.rst
regionmask/core/plot.py
regionmask/core/regions.py
regionmask/tests/test_Regions.py
regionmask/tests/test_plot.py

I found that float indices do not work currently. This allows them. I am not 100% sure that is the best idea, and if they should not be cast to int instead. Bet let's do this for now. In doing so, I found that there several optimizations that are possible.
This will need #477 and #477 will need this to pass - oh well

optimize `Regions` and allow float numbers

---

CHANGELOG.rst
regionmask/defined_regions/__init__.py
regionmask/defined_regions/_natural_earth.py
regionmask/tests/test_defined_regions.py
regionmask/tests/utils.py

I wanted to wait with removing `regionmask.defined_regions.natural_earth` because this was used widely. Hoever, to fix #410 I want to add the 5.1.2 natural earth version and don't want to do this with the old stuff around. So I raise an informative `AttributeError` instead. Allows to remove a lot specal case code, which is always nice.

removed natural_earth defined_region (cartopy)

---

CHANGELOG.rst
regionmask/core/_geopandas.py
regionmask/core/regions.py
regionmask/tests/test_Regions.py
regionmask/tests/test_geopandas.py

fix overlap default and docstring in from_* methods

---

CHANGELOG.rst
regionmask/core/regions.py
regionmask/tests/test_Regions.py
regionmask/tests/test_mask.py
regionmask/tests/test_plot.py

deprecate Regions.coords

---

CHANGELOG.rst
regionmask/core/mask.py
regionmask/tests/test_mask.py

Again, very interesting that no one ever raised this issue. I do see float32 data in netCDF files from time to time...

fix masks for float32 coords

---

docs/conf.py
docs/notebooks/method.ipynb
docs/notebooks/tutorial_rst.tpl

Sometimes rtd times out in the first cell of the method.ipynb notebook, which does:
```python
%matplotlib inline
from matplotlib import rcParams
rcParams["figure.dpi"] = 300
rcParams["font.size"] = 8
import warnings
warnings.filterwarnings("ignore")
```
I'll to see if not having `%matplotlib inline` is faster. But as this is flaky behavior, we will probably not find out right now...

rtd: test don't use `%matplotlib inline`

---

CHANGELOG.rst
docs/defined_countries.rst
docs/defined_landmask.rst
docs/defined_ocean_basins.rst
regionmask/core/utils.py
regionmask/defined_regions/__init__.py
regionmask/defined_regions/_natural_earth.py
regionmask/tests/test_defined_regions.py
regionmask/tests/test_mask_defined_regions.py
regionmask/tests/test_snap.py
regionmask/tests/utils.py

This fixes regions not extending to 180°E or 90°S when they should. This concerns:
- ocean_basins_50
- land_50
- countries_50
For
- natural_earth_v4_1_0 (already in regionmask)
- natural_earth_v5_0_0 (already in regionmask)
- natural_earth_v5_1_2 (new)
I will certainly fix it for the new regions. But I am not sure what to do about the the ones that are already in regionmask:
- warn to to switch to the new one? (this is what I currently implemented)
- fix and warn?
- silently fix?
cc @senclimate @pochedls - do you have an option?

fix_regions not extending to 180°E/ 90°S, add natural_earth_v5_1_2

---

CHANGELOG.rst
regionmask/core/mask.py

mask_to_dataarray: avoid internal xarray method

---

regionmask/core/mask.py

Fix for https://github.com/rasterio/rasterio/issues/3043. Not really necessary, but I want to get upsream-dev running.

fix rasterio dev dtype

---

CHANGELOG.rst
regionmask/tests/test_plot.py

cartopy: FeatureArtist is now a collection

---

CHANGELOG.rst
regionmask/tests/test_plot.py

It's a workaround, but should not matter here (not clear if one or the other approach is in any way better).

workaround for matplotlib-numpy v2 failures

---

ci/min_deps_check.py

Show the age of the 'user-requested' package (i.e. the one in min-all-deps.yml) and not of the 'policy-required' when running min_deps_check.py.

min_deps_check: show age of required pkg on error

---

CHANGELOG.rst
ci/requirements/min-all-deps.yml
docs/installation.rst
requirements.txt
setup.cfg

bump rasterio to v1.3

---

CHANGELOG.rst
ci/requirements/min-all-deps.yml
docs/source/installation.rst
requirements.txt
setup.cfg

Relatively aggressive bump of versions (for my standards) but might still be a moment before a new version comes out. Necessary preparation for #521

bump versions of dependencies

---

CHANGELOG.rst
ci/requirements/min-all-deps.yml
docs/source/installation.rst

We can bump pygrio again after requiring shapely v2.0+

bump pyogrio

---

regionmask/core/_geopandas.py
regionmask/core/regions.py

I will remove the function `_deprecate_positional_args` in a separate PR

finalize deprecate positional args

---

CHANGELOG.rst
regionmask/core/mask.py

Avoids `shapely.verctorized` which may be removed in the future shapely/shapely/issues/1630. In shapely v2 this is no longer faster/ optimized.

avoid shapely.vectorized

---

.github/workflows/ci.yaml
.github/workflows/upstream-dev-ci.yaml
CHANGELOG.rst
setup.cfg

Interested to see if the dependencies are ready...

add python 3.13 to supported versions

---

.github/workflows/ci.yaml
regionmask/core/formatting.py
regionmask/core/plot.py
setup.cfg

Maybe it was not the update of codecov but the config change?

fix coverage report

---

CHANGELOG.rst
regionmask/core/mask.py
regionmask/tests/test_create_dataarray.py

It's no longer accessible from `mask*` - so might as well.

finalize deprecation of lat_name and lon_name

---

docs/source/defined_scientific.rst
docs/source/notebooks/geopandas.ipynb
docs/source/notebooks/mask_3D_frac_approx.ipynb
pyproject.toml
regionmask/core/coords.py
regionmask/defined_regions/__init__.py
regionmask/defined_regions/_ar6.py
regionmask/defined_regions/_natural_earth.py
regionmask/defined_regions/_resources.py
regionmask/defined_regions/giorgi.py
regionmask/tests/test_mask.py
regionmask/tests/test_mask_cf_xarray.py
regionmask/tests/test_options.py

Using the [typos](https://github.com/crate-ci/typos) project. 
```
conda install typos
typos
typos -w
```
Note - it's necessary to double check the suggestions. Turns out I don't know how to write resources (it has two _s_ in the German _Ressourcen_)

fix misspelled words (using typos)

---

.readthedocs.yml
ci/requirements/docs.yml

remove rtd download workaround (from #570)
