regionmask/regionmask

docs/whats_new.rst, regionmask/core/mask.py, regionmask/test/test_mask.py
=> named xarray mask

docs/whats_new.rst, regionmask/defined_regions/giorgi.py
=> resolved conflicting Giorgi regions (#17)

docs/whats_new.rst, regionmask/core/plot.py, regionmask/core/regions.py, regionmask/test/test_OneRegion_and_Region_cls.py, regionmask/test/test_plot.py
=> close region plots when subsample=False

docs/whats_new.rst, regionmask/core/regions.py, regionmask/test/test_Regions.py, regionmask/test/test_Regions_cls.py
=> Deprecate centroids

docs/installation.rst, docs/whats_new.rst, regionmask/core/mask.py, regionmask/test/test_mask.py, requirements.txt
=> Require xarray

.travis.yml, docs/api.rst, docs/whats_new.rst, regionmask/__init__.py, regionmask/core/mask.py, regionmask/core/utils.py, regionmask/test/test_mask.py, regionmask/test/test_utils.py, requirements.txt
=> feature: rasterize using rasterio

docs/conf.py, docs/environment.yml, docs/index.rst, docs/notebooks/new_behavior.ipynb, docs/whats_new.rst
=> add doc on algorithm

docs/whats_new.rst, regionmask/test/test_mask_defined_regions.py
=> add regionmask/test/test_mask_defined_regions.py

docs/defined_ocean_basins.rst, docs/index.rst, docs/whats_new.rst, regionmask/defined_regions/natural_earth.py, regionmask/test/test_defined_regions.py, regionmask/test/test_mask_defined_regions.py
Adds ocean regions to the natural earth module.
=> added ne_50m_physical_geography_marine_polys

.travis.yml
See: conda-forge/fiona-feedstock/issues/159
=> pin libnetcdf

docs/whats_new.rst, regionmask/defined_regions/natural_earth.py, regionmask/test/test_defined_regions.py
=> read naturalearth as utf8

docs/whats_new.rst, regionmask/test/test_mask.py
=> test Polygon with z-coordinates

codecov.yml, docs/whats_new.rst
Let's see if I now get a code coverage report
=> enable codecov

docs/whats_new.rst, regionmask/defined_regions/natural_earth.py, regionmask/test/test_defined_regions.py
=> Update maybe get column

docs/api.rst, docs/conf.py, docs/whats_new.rst, regionmask/core/_geopandas.py, regionmask/core/plot.py, regionmask/core/regions.py
=> Enable sphinx.ext.napoleon

docs/whats_new.rst, licences/XARRAY_LICENSE, regionmask/core/formatting.py, regionmask/core/regions.py, regionmask/test/test_formatting.py
=> New regions repr

docs/whats_new.rst, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/test/test_Regions.py, regionmask/test/test_geopandas.py, regionmask/test/test_utils.py
=> Assert numbers are nummeric

ci/requirements/py27.yml, ci/requirements/py36.yml, ci/requirements/py37.yml, ci/requirements/py38.yml, docs/whats_new.rst
=> use matplotlib-base for tests

docs/whats_new.rst, regionmask/core/mask.py, regionmask/core/utils.py, regionmask/test/test_mask.py, regionmask/test/test_mask_defined_regions.py, regionmask/test/test_utils.py
=> rasterio: split lon if possible

docs/api.rst, docs/conf.py, docs/environment_rtd.yml, docs/index.rst, docs/notebooks/geopandas.ipynb, docs/notebooks/mask_2D.ipynb, docs/notebooks/mask_3D.ipynb, docs/whats_new.rst, regionmask/__init__.py, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/test/test_geopandas.py, regionmask/test/test_mask.py, regionmask/test/utils.py
=> WIP: mask 3D

docs/whats_new.rst, regionmask/core/plot.py, regionmask/test/test_mask.py, regionmask/test/test_plot.py
=> More plot kws

docs/whats_new.rst, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/test/test_OneRegion_and_Region_cls.py, regionmask/test/test_mask.py, regionmask/test/test_utils.py
=> Remove asserts

docs/whats_new.rst, regionmask/test/test_plot.py
=> use context manager for plot tests

docs/whats_new.rst, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/test/test_geopandas.py, regionmask/test/test_mask.py
=> fix warning on empty mask

docs/whats_new.rst, regionmask/core/plot.py, regionmask/test/test_plot.py
=> do not subset long coords

azure-pipelines.yml, ci/azure/install.yml, ci/min_deps_check.py, ci/requirements/py36-min-all-deps.yml, regionmask/core/plot.py, regionmask/test/test_plot.py
This is not yet super relevant as I still have a python 2.7 enviroment. But it's already prepared once I drop py27.
=> Minimum version policy

regionmask/core/plot.py, regionmask/defined_regions/natural_earth.py
isort v5 also sorts imports in functions
=> fix imports for isort v5.1

docs/notebooks/method.ipynb, docs/whats_new.rst, regionmask/core/mask.py, regionmask/test/test_mask.py
=> Treat points at -180°E 0°E and -90°N

docs/whats_new.rst, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/test/test_mask.py
=> unify mask docstrings

setup.py
=> fix missing long_description_content_type

docs/notebooks/mask_2D.ipynb, docs/whats_new.rst
=> mention regional median calculation

docs/whats_new.rst, regionmask/core/plot.py, regionmask/test/test_plot.py
=> clip text labels outside map

docs/whats_new.rst, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/test/test_mask.py
=> remove xarray keyword of mask fcns

docs/api.rst, docs/whats_new.rst, regionmask/__init__.py, regionmask/core/mask.py, regionmask/test/test_mask.py
=> remove create_mask_contains

docs/notebooks/method.ipynb, docs/whats_new.rst, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/test/test_geopandas.py, regionmask/test/test_mask.py
=> remove_legacy_masking

docs/defined_scientific.rst, docs/whats_new.rst, regionmask/core/plot.py, regionmask/test/test_plot.py
=> label all Polygons of MultiPolygons

setup.cfg
=> isort: use profile: black

ci/requirements/py36.yml, ci/requirements/py37.yml, ci/requirements/py38.yml, docs/whats_new.rst, requirements.txt
=> add scipy to requirements

regionmask/test/test_formatting.py
Update the formatting of the repr, as pandas made a small change.
=> fix pandas formatting test

docs/whats_new.rst, regionmask/core/regions.py, regionmask/test/test_Regions.py
=> ensure regions are sorted

docs/whats_new.rst, regionmask/version.py
=> Release v0.6.2

docs/whats_new.rst, regionmask/core/plot.py, regionmask/core/utils.py, regionmask/tests/test_plot.py
=> move and harden _flatten_polygons

docs/defined_landmask.rst
For got to mention the new regions in the docs.
=> add docs for landmask 10 & 50

azure-pipelines.yml, ci/requirements/py39.yml, docs/whats_new.rst, regionmask/core/mask.py
=> add test environment for py39

ci/requirements/py36-min-all-deps.yml, docs/installation.rst, docs/whats_new.rst, regionmask/core/mask.py, regionmask/core/plot.py, regionmask/tests/test_plot.py, requirements.txt
=> bump versions

azure-pipelines.yml, regionmask/core/plot.py
The linting step did not fail when one of the parts (e.g. black) failed.
=> split linting steps

docs/conf.py, docs/installation.rst, docs/intake_regionmask.rst, docs/notebooks/method.ipynb, docs/whats_new.rst, regionmask/defined_regions/_ressources.py, regionmask/tests/test_mask.py, setup.py
=> move repo to regionmask organisation

HOW_TO_RELEASE.md
=> add release instructions

HOW_TO_RELEASE.md, README.rst, docs/whats_new.rst, regionmask/version.py
=> Release v0.7.0

docs/whats_new.rst, requirements.txt, setup.cfg, setup.py
=> setup options to setup.cfg

.git_archival.txt, .gitattributes, HOW_TO_RELEASE.md, MANIFEST.in, ci/requirements/environment.yml, ci/requirements/py36-bare-minimum.yml, ci/requirements/py36-min-all-deps.yml, docs/whats_new.rst, pyproj.toml, regionmask/__init__.py, regionmask/version.py, setup.cfg, setup.py
=> use setuptools_scm and pyproj.toml

.github/workflows/ci-additional.yaml, .github/workflows/ci.yaml
github actions hangs from time to time - try `python -u` to "Force the stdout and stderr streams to be unbuffered.", see: https://docs.python.org/3/using/cmdline.html#cmdoption-u
=> gh actions: set timeout

ci/min_deps_check.py, ci/requirements/environment.yml, ci/requirements/py36-bare-minimum.yml, ci/requirements/py36-min-all-deps.yml, regionmask/tests/test_defined_regions.py, regionmask/tests/test_mask_defined_regions.py, setup.cfg
Let's see if this helps with the timeouts in the tests (#256) - maybe helps to make them non-silent...
=> try pytest-timeout

.github/workflows/ci.yaml, ci/min_deps_check.py, ci/requirements/py36-min-all-deps.yml, docs/whats_new.rst, regionmask/tests/test_defined_regions.py, regionmask/tests/test_mask_defined_regions.py, regionmask/tests/utils.py, setup.cfg
=> tests: ne_download timeout to warning

docs/notebooks/method.ipynb, docs/whats_new.rst, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/tests/test_geopandas.py, regionmask/tests/test_mask.py, regionmask/tests/test_utils.py, regionmask/tests/test_wrapAngle.py
=> fix: wrap_lon=False

docs/whats_new.rst, regionmask/core/_geopandas.py
=> pd.Series.str.replace: regex=True

docs/whats_new.rst, regionmask/core/mask.py, regionmask/tests/test_mask.py, regionmask/tests/test_mask_defined_regions.py
=> fix asymmetric flip_lon (#266)

regionmask/tests/test_mask.py, regionmask/tests/test_mask_defined_regions.py
Small updates to the tests. More could be done.
=> small mask test updates

docs/notebooks/method.ipynb
Fixes the plots in the method.ipynb notebook - see SciTools/cartopy#1845
=> fix method notebook plots (SciTools/cartopy#1845)

docs/whats_new.rst
=> Release v0.8.0

HOW_TO_RELEASE.md, README.rst
=> update zenodo link

.github/workflows/ci-additional.yaml, docs/whats_new.rst, regionmask/tests/test_defined_regions.py, regionmask/tests/utils.py
=> Fix ne download

.github/workflows/ci-additional.yaml, .github/workflows/ci.yaml
=> GH: update codecov/codecov-action version

docs/whats_new.rst, regionmask/core/mask.py, regionmask/tests/test_create_dataarray.py
=> BUG: wrong dim order

ci/requirements/py37-min-all-deps.yml, regionmask/defined_regions/natural_earth.py, regionmask/tests/test_defined_regions.py, regionmask/tests/utils.py
=> fix naturaleath (v5.0)  updates

regionmask/tests/__init__.py
`distutils.version` is deprecated use `packaging.version` instead
=> use packaging.version

docs/Makefile, docs/README_ipynp_for_RTD, docs/clean_notebooks, docs/defined_countries.rst, docs/defined_ocean_basins.rst, docs/defined_scientific.rst, docs/notebooks/method.ipynb, docs/whats_new.rst
Small doc fixes suggested by sphinx and atom ;-)
=> Small doc fixes

ci/min_deps_check.py, ci/requirements/py37-min-all-deps.yml, docs/installation.rst, docs/whats_new.rst, requirements.txt, setup.cfg
Bump minimum versions for the next release.
=> bump min versions

README.rst, ci/requirements/docs.yml, docs/defined_scientific.rst, docs/index.rst, docs/installation.rst, docs/notebooks/create_own_regions.ipynb, docs/notebooks/geopandas.ipynb, docs/notebooks/mask_2D.ipynb, docs/notebooks/mask_3D.ipynb, docs/notebooks/method.ipynb, docs/notebooks/plotting.ipynb, docs/notebooks/tutorial_rst.tpl, docs/whats_new.rst, pyproject.toml, readthedocs.yml, regionmask/__init__.py
=> doc updates

regionmask/core/mask.py, regionmask/tests/test_mask.py, regionmask/tests/test_segmentize.py, regionmask/tests/test_utils.py
New formatting of `**` with the new black release.
=> black 2022.01

.github/workflows/ci-additional.yaml, .github/workflows/ci.yaml, .github/workflows/linting.yaml, docs/whats_new.rst, setup.cfg
Let's see if all dependencies are ready.
=> support python 3.10

HOW_TO_RELEASE.md
No longer have a stable branch.
=> update how to release

regionmask/defined_regions/_natural_earth.py
A bit nicer than creating a fake registry.
=> use pooch.retrieve

regionmask/core/formatting.py, regionmask/core/regions.py, regionmask/defined_regions/_natural_earth.py, regionmask/tests/test_OneRegion.py, regionmask/tests/test_Regions.py
Some code updates:
- make `_OneRegion.centroid` lazy
- run pyupgrade (`find . -name "*.py" -exec pyupgrade --py37-plus {} \`)
=> code updates (layzy centroid & pyupgrade)

regionmask/core/plot.py, regionmask/core/regions.py, regionmask/defined_regions/_natural_earth.py
=> velin & doc fixes

docs/whats_new.rst
=> Release v0.9.0

docs/whats_new.rst
new whatsnew section for v0.10.0
=> new whatsnew section

docs/whats_new.rst, regionmask/core/mask.py
=> vectorize _mask_edgepoints_shapely

docs/whats_new.rst, regionmask/core/mask.py
=> shapely & pygeos: directly create 3D masks

docs/whats_new.rst, regionmask/core/mask.py
=> rasterio: directly create 3D masks

ci/requirements/docs.yml, docs/conf.py
Try to fix the readthedocs build.
=> rtd: set PROJ_LIB env var

.git_archival.txt
=> fix .git_archival

.github/workflows/ci-additional.yaml, .github/workflows/ci.yaml, .github/workflows/linting.yaml
Let's see if this works and is actually faster.
=> mamba & micromamba for CI

regionmask/core/_deprecate.py, regionmask/core/options.py, regionmask/core/regions.py
Some fixes to the docstring. Make the docstring examples run with doctest.
=> docstring fixes (velin and examples)

docs/whats_new.rst, regionmask/core/utils.py
=> optimize unpackbits

README.rst
=> fix conda badge

regionmask/tests/test_plot.py
Not all figures were closed during the tests.
=> ensure plot tests close all figures

docs/conf.py, regionmask/core/_deprecate.py, regionmask/core/_geopandas.py, regionmask/core/formatting.py, regionmask/core/mask.py, regionmask/core/options.py, regionmask/core/plot.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/defined_regions/_ar6.py, regionmask/defined_regions/_ar6_pre_revisions.py, regionmask/defined_regions/_natural_earth.py, regionmask/defined_regions/_ressources.py, regionmask/tests/__init__.py, regionmask/tests/test_OneRegion.py, regionmask/tests/test_Regions.py, regionmask/tests/test_create_dataarray.py, regionmask/tests/test_defined_regions.py, regionmask/tests/test_formatting.py, regionmask/tests/test_geopandas.py, regionmask/tests/test_mask.py, regionmask/tests/test_mask_defined_regions.py, regionmask/tests/test_options.py, regionmask/tests/test_plot.py, regionmask/tests/test_segmentize.py, regionmask/tests/test_utils.py, regionmask/tests/test_wrapAngle.py, regionmask/tests/utils.py
Again not the biggest fan of this style change... As the code shows - I make ample use of a newline after a block statement...
=> apply black 23.01

.github/workflows/ci-additional.yaml, .github/workflows/ci.yaml, .github/workflows/linting.yaml
Pins the version of micromamba - should be updated with dependabot. This pins it to the older 13 version so dependabot should issue a PR soon.
=> micromamba: pin version

docs/defined_countries.rst, docs/whats_new.rst, regionmask/defined_regions/_natural_earth.py, regionmask/tests/test_mask_defined_regions.py, regionmask/tests/utils.py
=> add countries 10m (natural earth)

docs/conf.py, regionmask/core/_deprecate.py, regionmask/core/_geopandas.py, regionmask/core/formatting.py, regionmask/core/mask.py, regionmask/core/plot.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/defined_regions/_ar6.py, regionmask/defined_regions/_ar6_pre_revisions.py, regionmask/defined_regions/_natural_earth.py, regionmask/defined_regions/_ressources.py, regionmask/tests/__init__.py, regionmask/tests/test_OneRegion.py, regionmask/tests/test_Regions.py, regionmask/tests/test_create_dataarray.py, regionmask/tests/test_defined_regions.py, regionmask/tests/test_formatting.py, regionmask/tests/test_geopandas.py, regionmask/tests/test_mask.py, regionmask/tests/test_mask_defined_regions.py, regionmask/tests/test_options.py, regionmask/tests/test_plot.py, regionmask/tests/test_segmentize.py, regionmask/tests/test_utils.py, regionmask/tests/test_wrapAngle.py, regionmask/tests/utils.py
This reverts commit 92ce10a6a4364df76143a5ddee5073f591f1c024.
undo this unholy mess
=> Revert "apply black 23.01 (#397)"

regionmask/core/coords.py
=> mention cf_xarray on coord KeyError

docs/api.rst, docs/whats_new.rst, regionmask/__init__.py, regionmask/core/plot.py, regionmask/core/utils.py, regionmask/tests/test_utils.py
=> add flatten_3D_mask func

docs/notebooks/mask_2D.ipynb, docs/whats_new.rst
I think there is no blocking issue/ pending PR.
=> release v0.10.0

docs/whats_new.rst, regionmask/core/mask.py, regionmask/tests/test_mask.py
=> Fix edgepoints nan lon

regionmask/core/mask.py, regionmask/defined_regions/_ar6_pre_revisions.py, regionmask/tests/test_defined_regions.py, regionmask/tests/test_mask.py
Add when something was deprecated to make it easier for future me.
=> add versions for deprecations

docs/whats_new.rst, regionmask/core/mask.py, regionmask/core/regions.py
=> mask_2D: better overlap errmsg

docs/whats_new.rst, regionmask/core/mask.py
=> small refactor

docs/whats_new.rst, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/tests/test_utils.py
=> internal _mask fcns: update signature

.github/workflows/upstream-dev-ci.yaml, ci/install-upstream-wheels.sh, docs/whats_new.rst
=> test upstream

CHANGELOG.rst, ci/requirements/docs.yml, docs/changelog.rst, docs/conf.py, docs/index.rst
=> rename whats new to changelog

CHANGELOG.rst
=> release v0.11.0

CHANGELOG.rst, HOW_TO_RELEASE.md, README.rst
=> New changelog section

ci/install-upstream-wheels.sh
=> upstream_ci: use xarray wheels

regionmask/core/utils.py
=> _total_bounds: remove stray computation

regionmask/__init__.py, regionmask/core/_geopandas.py, regionmask/defined_regions/_natural_earth.py, regionmask/tests/__init__.py, regionmask/tests/test_formatting.py, regionmask/tests/test_segmentize.py, regionmask/tests/utils.py
=> remove no-longer-used version checks & cleanups

regionmask/core/options.py, regionmask/tests/test_options.py
=> more tests for get_options set_options

CHANGELOG.rst, data/regions_remote_catalog.yaml, docs/intake_regionmask.rst
Second try to fix the links to the MEOW data after #474 - I forgot some in the rst file.
Edit: I (partially) restructured the regionmask-intake tutorial, it should now instantly render.
=> update intake regionmask example and fix MEOW url

ci/min_deps_check.py
=> fix fstring

regionmask/defined_regions/_ar6.py, regionmask/defined_regions/_natural_earth.py
not really necessary but its a bit less code
=> defined_regions: use @cache

docs/api.rst, regionmask/core/mask.py, regionmask/core/plot.py
=> doc(string) fixes

ci/min_deps_check.py, docs/conf.py, regionmask/core/coords.py, regionmask/core/mask.py, regionmask/defined_regions/__init__.py, regionmask/defined_regions/giorgi.py
=> formatting fixes

.github/workflows/ci.yaml, .github/workflows/linting.yaml, .github/workflows/upstream-dev-ci.yaml, CHANGELOG.rst, ci/requirements/docs.yml, setup.cfg
=> add python 3.12 to supported versions

ci/requirements/py310-shapely_lt_2.yml, ci/requirements/py39-bare-minimum.yml, regionmask/core/coords.py, regionmask/tests/test_OneRegion.py, regionmask/tests/test_mask.py, regionmask/tests/test_mask_cf_xarray.py
=> more tests; pin shapely=1.8 in bare-minimum CI

CHANGELOG.rst, README.md, docs/conf.py, docs/index.rst, docs/notebooks/mask_3D_frac_approx.ipynb, docs/notebooks/method_mask_3D_frac_approx.ipynb, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/tests/test_mask.py, regionmask/tests/test_mask_3D_frac_approx.py
There is still a lot of docs missing. Also the method is memory intensive and only precise to about 0.05 (5 %). But here it is - after 4 years...
=> mask 3D frac approx

.readthedocs.yml
Split off/ cherry picked from #450
=> update rtd tools and config

.github/workflows/pypi-release.yaml, HOW_TO_RELEASE.md
The same as for xarray. Added a Trusted Publisher to pypi and test.pypi.
=> GitHub action for publishing to PyPI

regionmask/__init__.py, regionmask/core/_geopandas.py, regionmask/core/mask.py, regionmask/core/plot.py, regionmask/core/regions.py, regionmask/defined_regions/__init__.py, regionmask/defined_regions/_ar6.py, regionmask/defined_regions/_natural_earth.py, regionmask/defined_regions/giorgi.py, regionmask/defined_regions/prudence.py, regionmask/defined_regions/srex.py, regionmask/tests/test_defined_regions.py, regionmask/tests/test_geopandas.py, regionmask/tests/test_mask.py, regionmask/tests/test_mask_3D_frac_approx.py, regionmask/tests/test_mask_cf_xarray.py, regionmask/tests/test_mask_defined_regions.py, regionmask/tests/test_plot.py, regionmask/tests/test_segmentize.py
=> absolutify imports

docs/logo/logo.ipynb, docs/notebooks/create_own_regions.ipynb, docs/notebooks/geopandas.ipynb, docs/notebooks/mask_2D.ipynb, docs/notebooks/mask_3D.ipynb, docs/notebooks/mask_3D_frac_approx.ipynb, docs/notebooks/method.ipynb, pyproject.toml
Also checks notebooks which is nice. Switch away from black and isort later (and keep black for the moment as they just fixed the newline thingy, which ruff still has),
=> add ruff configuration

regionmask/tests/test_deprecate.py, regionmask/tests/test_options.py
Especially the second one is relevant.
=> ensure arguments are used

CHANGELOG.rst
=> release v0.12.0

CHANGELOG.rst, setup.cfg
=> release v0.12.1

.github/workflows/pypi-release.yaml
=> test_pypi: fix repo url

ci/install-upstream-wheels.sh
Let's try if this fixes the upstream dev CI.
=> upsream_ci: install shapely dev version

ci/install-upstream-wheels.sh
Should speed up building the environment.
=> upstream dev CI: use nightly shapely wheels

docs/api.rst
This was forgotten when I added the method.
=> add mask_3D_frac_approx to api docs

README.md
After moving the docs to a source folder
=> fix logo path for README

regionmask/core/utils.py
Follow up to #521 - there was more stuff we can simplify now that we require shapely v2.0.
=> more shapely v2 cleanup

regionmask/tests/test_geopandas.py
=> more geopandas tests

ci/requirements/bare-minimum.yml
- [y] Closes #471
Finally! (Although of course a lower coverage can sneak in anytime)
=> pin geopandas to test w/o pyogrio 

.github/workflows/ci.yaml, CHANGELOG.rst, ci/requirements/bare-minimum.yml, ci/requirements/min-all-deps.yml, docs/source/installation.rst, pyproject.toml, regionmask/core/_geopandas.py, regionmask/core/coords.py, regionmask/core/options.py, regionmask/core/regions.py, regionmask/tests/utils.py, setup.cfg
=> drop python 3.9 support

CHANGELOG.rst, docs/source/api.rst, regionmask/core/regions.py, regionmask/tests/test_Regions.py
I don't expect anyone to actually use this but let's deprecate anyway...
=> make region_ids property private

.readthedocs.yml, CHANGELOG.rst, ci/requirements/docs.yml, docs/source/conf.py, regionmask/defined_regions/_ressources.py
xref dask/dask-sphinx-theme#91 & readthedocs/readthedocs.org#11763
=> FIX: rtd github download

CHANGELOG.rst, regionmask/tests/test_OneRegion.py, regionmask/tests/test_Regions.py, regionmask/tests/test_create_dataarray.py, regionmask/tests/test_defined_regions.py, regionmask/tests/test_formatting.py, regionmask/tests/test_geopandas.py, regionmask/tests/test_mask.py, regionmask/tests/test_mask_3D_frac_approx.py, regionmask/tests/test_mask_cf_xarray.py, regionmask/tests/test_mask_defined_regions.py, regionmask/tests/test_options.py, regionmask/tests/test_plot.py, regionmask/tests/test_segmentize.py, regionmask/tests/test_snap.py, regionmask/tests/test_utils.py, regionmask/tests/test_wrapAngle.py
=> type check tests

CHANGELOG.rst, regionmask/core/mask.py, regionmask/core/options.py, regionmask/core/regions.py, regionmask/tests/test_mask_3D_frac_approx.py, regionmask/tests/test_options.py, regionmask/tests/test_plot.py, setup.cfg
=> (partially) type `Regions` and `mask*`

CHANGELOG.rst, regionmask/core/_geopandas.py, regionmask/tests/test_geopandas.py
=> type geopandas functions

CHANGELOG.rst, regionmask/core/options.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/tests/test_options.py, regionmask/tests/utils.py
=> TYP: `--check-untyped-defs`

CHANGELOG.rst, regionmask/core/_geopandas.py, regionmask/core/formatting.py, regionmask/core/mask.py, regionmask/core/regions.py, regionmask/core/utils.py, regionmask/defined_regions/_natural_earth.py, regionmask/tests/test_defined_regions.py, regionmask/tests/test_geopandas.py
=> type utils and formatting

setup.cfg
=> ignore TYPE_CHECKING for coverage

CHANGELOG.rst, regionmask/core/plot.py, regionmask/tests/test_plot.py
=> add py.typed

pyproject.toml, regionmask/core/mask.py, regionmask/tests/test_mask.py
=> typing and other nits

.github/workflows/ci-additional.yaml
=> try minimum-dependency-versions

CHANGELOG.rst
=> release v0.13.0

CHANGELOG.rst, regionmask/core/mask.py
=> internal mask fcns: make more args kw only

CHANGELOG.rst, regionmask/core/_geopandas.py, regionmask/core/coords.py, regionmask/core/mask.py, regionmask/core/utils.py, regionmask/tests/test_create_dataarray.py
Finally got around to type many of the params. Also found a minor bug.
=> more typing, especially parameters

CHANGELOG.rst, docs/source/conf.py, docs/source/defined_countries.rst, docs/source/defined_landmask.rst, docs/source/defined_ocean_basins.rst, docs/source/defined_scientific.rst, docs/source/installation.rst, docs/source/notebooks/detect_coords.ipynb, docs/source/notebooks/mask_2D.ipynb, docs/source/notebooks/mask_3D.ipynb, docs/source/notebooks/mask_3D_frac_approx.ipynb, docs/source/notebooks/method.ipynb, licences/XARRAY_LICENSE, regionmask/core/regions.py, regionmask/defined_regions/_natural_earth.py, regionmask/defined_regions/giorgi.py, regionmask/defined_regions/srex.py, regionmask/tests/test_defined_regions.py
=> fix links with sphinx linkcheck

.github/workflows/ci.yaml, CHANGELOG.rst, ci/requirements/bare-minimum.yml, ci/requirements/min-all-deps.yml, docs/source/installation.rst, pyproject.toml, regionmask/core/options.py
=> drop python 3.10 support
